In [55]:
import pandas as pd
import matplotlib.pyplot as plt
import json
import os
from pathlib import Path

In [56]:
explanations_shap = []
explanations_lime = []

experiments_path = Path('experiment_explanations')

for pasta_filha in experiments_path.iterdir():
    if pasta_filha.is_dir():
        # Buscar arquivos LIME
        lime_file = pasta_filha / 'lime_results.json'
        if lime_file.exists():
            with open(lime_file, 'r', encoding='utf-8') as f:
                lime_data = json.load(f)
                explanations_lime.append({
                    'experiment': pasta_filha.name,
                    'data': lime_data
                })
        
        shap_file = pasta_filha / 'shap_results.json'
        if shap_file.exists():
            with open(shap_file, 'r', encoding='utf-8') as f:
                shap_data = json.load(f)
                explanations_shap.append({
                    'experiment': pasta_filha.name,
                    'data': shap_data
                })

print(f"Encontrados {len(explanations_lime)} arquivos LIME")
print(f"Encontrados {len(explanations_shap)} arquivos SHAP")

Encontrados 20 arquivos LIME
Encontrados 20 arquivos SHAP

In [57]:
print(explanations_shap[0]['data'])

{'global_importance': [0.000825980077888965, 6.372441534129996e-07, 0.001175594449572799, 0.0, 3.413015401617674e-05, 4.0860087637389245e-06, 1.5014964976303637e-06, 9.888381247024395e-05, 0.0], 'local_explanation': [0.002121008981196651, 0.0, -0.004309205352373063, 0.0, 0.00016668923811188657, 0.0, 0.0, 0.0003015707026102706, 0.0], 'feature_names': ['MolWt', 'MolLogP', 'TPSA', 'NumHDonors', 'NumHAcceptors', 'NumRotatableBonds', 'NumAromaticRings', 'BalabanJ', 'QED'], 'model_type': 'Physicochemical_att0', 'timestamp': '2025-10-04T10:33:52.379644'}

In [58]:
list_desc_lime = [exp['data']['model_type'].split('_')[0] for exp in explanations_lime]

properties = [
            'Rotational constant A: GHz', 'Rotational constant B: GHz', 'Rotational constant C: GHz',
            'Dipole moment (μ): Debye (D)', 'Isotropic polarizability (α): atomic units (a.u.)',
            'Energy of HOMO (ϵHOMO): Hartree (Ha)', 'Energy of LUMO (ϵLUMO): Hartree (Ha)',
            'Gap (ϵgap): Hartree (Ha)', 'Electronic spatial extent: atomic units (a.u.)',
            'Zero point vibrational energy (zpve): Hartree (Ha)', 'Internal energy at 0 K (U0): Hartree (Ha)',
            'Internal energy at 298.15 K (U): Hartree (Ha)', 'Enthalpy at 298.15 K (H): Hartree (Ha)',
            'Free energy at 298.15 K (G): Hartree (Ha)', 'Heat capacity at 298.15 K (Cv): cal/mol·K'
            ]

prop_lime = []
for exp in explanations_lime:
    model_type = exp['data']['model_type']
    parts = model_type.split('_')
    att_part = parts[1]
    index = int(att_part[3:])
    prop_lime.append(properties[index])


descriptors_lime = {
    'descriptor': list_desc_lime,
    'predicted_property': prop_lime,
    'feature_names': [exp['data']['feature_names'] for exp in explanations_lime]
}

In [59]:
df_descriptors_lime = pd.DataFrame(descriptors_lime)

df_descriptors_lime

,descriptor,predicted_property,feature_names
0,Physicochemical,Rotational constant A: GHz,"[MolWt, MolLogP, TPSA, NumHDonors, NumHAccepto..."
1,3D,Internal energy at 0 K (U0): Hartree (Ha),"[NPR1, NPR2, RadiusOfGyration, Asphericity, Sp..."
2,EState,Internal energy at 0 K (U0): Hartree (Ha),"[EState_0, EState_1, EState_2, EState_3, EStat..."
3,Avalon,Rotational constant A: GHz,"[Avalon_Bit_0, Avalon_Bit_1, Avalon_Bit_2, Ava..."
4,CM,Internal energy at 0 K (U0): Hartree (Ha),"[CM_0_0, CM_0_1, CM_0_2, CM_0_3, CM_0_4, CM_0_..."
5,Pattern,Rotational constant A: GHz,"[Pattern_Bit_0, Pattern_Bit_1, Pattern_Bit_2, ..."
6,Topological,Internal energy at 0 K (U0): Hartree (Ha),"[Topo_Bit_0, Topo_Bit_1, Topo_Bit_2, Topo_Bit_..."
7,Morgan,Internal energy at 0 K (U0): Hartree (Ha),"[Morgan2_Bit_0, Morgan2_Bit_1, Morgan2_Bit_2, ..."
8,Pattern,Internal energy at 0 K (U0): Hartree (Ha),"[Pattern_Bit_0, Pattern_Bit_1, Pattern_Bit_2, ..."
9,EState,Rotational constant A: GHz,"[EState_0, EState_1, EState_2, EState_3, EStat..."
10,AtomPair,Rotational constant A: GHz,"[AtomPair_Bit_0, AtomPair_Bit_1, AtomPair_Bit_..."
11,Avalon,Internal energy at 0 K (U0): Hartree (Ha),"[Avalon_Bit_0, Avalon_Bit_1, Avalon_Bit_2, Ava..."
12,Topological,Rotational constant A: GHz,"[Topo_Bit_0, Topo_Bit_1, Topo_Bit_2, Topo_Bit_..."
13,MorganCount,Rotational constant A: GHz,"[Morgan2_Bit_0, Morgan2_Bit_1, Morgan2_Bit_2, ..."
14,AtomPair,Internal energy at 0 K (U0): Hartree (Ha),"[AtomPair_Bit_0, AtomPair_Bit_1, AtomPair_Bit_..."
15,Physicochemical,Internal energy at 0 K (U0): Hartree (Ha),"[MolWt, MolLogP, TPSA, NumHDonors, NumHAccepto..."
16,3D,Rotational constant A: GHz,"[NPR1, NPR2, RadiusOfGyration, Asphericity, Sp..."
17,MorganCount,Internal energy at 0 K (U0): Hartree (Ha),"[Morgan2_Bit_0, Morgan2_Bit_1, Morgan2_Bit_2, ..."
18,Morgan,Rotational constant A: GHz,"[Morgan2_Bit_0, Morgan2_Bit_1, Morgan2_Bit_2, ..."
19,CM,Rotational constant A: GHz,"[CM_0_0, CM_0_1, CM_0_2, CM_0_3, CM_0_4, CM_0_..."

In [60]:
list_desc_shap = [exp['data']['model_type'].split('_')[0] for exp in explanations_shap]

prop_shap = []
for exp in explanations_shap:
    model_type = exp['data']['model_type']
    parts = model_type.split('_')
    att_part = parts[1]
    index = int(att_part[3:])
    prop_shap.append(properties[index])


descriptors_shap = {
    'descriptor': list_desc_shap,
    'predicted_property': prop_shap,
    'feature_names': [exp['data']['feature_names'] for exp in explanations_shap]
}

In [61]:
df_descriptors_shap = pd.DataFrame(descriptors_shap)

df_descriptors_shap

,descriptor,predicted_property,feature_names
0,Physicochemical,Rotational constant A: GHz,"[MolWt, MolLogP, TPSA, NumHDonors, NumHAccepto..."
1,3D,Internal energy at 0 K (U0): Hartree (Ha),"[NPR1, NPR2, RadiusOfGyration, Asphericity, Sp..."
2,EState,Internal energy at 0 K (U0): Hartree (Ha),"[EState_0, EState_1, EState_2, EState_3, EStat..."
3,Avalon,Rotational constant A: GHz,"[Avalon_Bit_0, Avalon_Bit_1, Avalon_Bit_2, Ava..."
4,CM,Internal energy at 0 K (U0): Hartree (Ha),"[CM_0_0, CM_0_1, CM_0_2, CM_0_3, CM_0_4, CM_0_..."
5,Pattern,Rotational constant A: GHz,"[Pattern_Bit_0, Pattern_Bit_1, Pattern_Bit_2, ..."
6,Topological,Internal energy at 0 K (U0): Hartree (Ha),"[Topo_Bit_0, Topo_Bit_1, Topo_Bit_2, Topo_Bit_..."
7,Morgan,Internal energy at 0 K (U0): Hartree (Ha),"[Morgan2_Bit_0, Morgan2_Bit_1, Morgan2_Bit_2, ..."
8,Pattern,Internal energy at 0 K (U0): Hartree (Ha),"[Pattern_Bit_0, Pattern_Bit_1, Pattern_Bit_2, ..."
9,EState,Rotational constant A: GHz,"[EState_0, EState_1, EState_2, EState_3, EStat..."
10,AtomPair,Rotational constant A: GHz,"[AtomPair_Bit_0, AtomPair_Bit_1, AtomPair_Bit_..."
11,Avalon,Internal energy at 0 K (U0): Hartree (Ha),"[Avalon_Bit_0, Avalon_Bit_1, Avalon_Bit_2, Ava..."
12,Topological,Rotational constant A: GHz,"[Topo_Bit_0, Topo_Bit_1, Topo_Bit_2, Topo_Bit_..."
13,MorganCount,Rotational constant A: GHz,"[Morgan2_Bit_0, Morgan2_Bit_1, Morgan2_Bit_2, ..."
14,AtomPair,Internal energy at 0 K (U0): Hartree (Ha),"[AtomPair_Bit_0, AtomPair_Bit_1, AtomPair_Bit_..."
15,Physicochemical,Internal energy at 0 K (U0): Hartree (Ha),"[MolWt, MolLogP, TPSA, NumHDonors, NumHAccepto..."
16,3D,Rotational constant A: GHz,"[NPR1, NPR2, RadiusOfGyration, Asphericity, Sp..."
17,MorganCount,Internal energy at 0 K (U0): Hartree (Ha),"[Morgan2_Bit_0, Morgan2_Bit_1, Morgan2_Bit_2, ..."
18,Morgan,Rotational constant A: GHz,"[Morgan2_Bit_0, Morgan2_Bit_1, Morgan2_Bit_2, ..."
19,CM,Rotational constant A: GHz,"[CM_0_0, CM_0_1, CM_0_2, CM_0_3, CM_0_4, CM_0_..."

In [68]:
top1_lime = []
top2_lime = []
top3_lime = []
top4_lime = []
top5_lime = []

features_lime = []

for exp in explanations_lime:
    local_exp = exp['data']['local_explanation']
    features_lime = exp['data']['feature_names'] 

    indexed_exp = [(i, val) for i, val in enumerate(local_exp)]
    
    sorted_exp = sorted(indexed_exp, key=lambda x: abs(x[1]), reverse=True)
    
    top1_lime.append(features_lime[sorted_exp[0][0]] if len(sorted_exp) > 0 else None)
    top2_lime.append(features_lime[sorted_exp[1][0]] if len(sorted_exp) > 1 else None)
    top3_lime.append(features_lime[sorted_exp[2][0]] if len(sorted_exp) > 2 else None)
    top4_lime.append(features_lime[sorted_exp[3][0]] if len(sorted_exp) > 3 else None)
    top5_lime.append(features_lime[sorted_exp[4][0]] if len(sorted_exp) > 4 else None)

top1_shap = []
top2_shap = []
top3_shap = []
top4_shap = []
top5_shap = []

features_shap = []

for exp in explanations_shap:
    local_exp = exp['data']['local_explanation']
    features_shap = exp['data']['feature_names'] 

    indexed_exp = [(i, val) for i, val in enumerate(local_exp)]
    
    sorted_exp = sorted(indexed_exp, key=lambda x: abs(x[1]), reverse=True)
    
    top1_shap.append(features_shap[sorted_exp[0][0]] if len(sorted_exp) > 0 else None)
    top2_shap.append(features_shap[sorted_exp[1][0]] if len(sorted_exp) > 1 else None)
    top3_shap.append(features_shap[sorted_exp[2][0]] if len(sorted_exp) > 2 else None)
    top4_shap.append(features_shap[sorted_exp[3][0]] if len(sorted_exp) > 3 else None)
    top5_shap.append(features_shap[sorted_exp[4][0]] if len(sorted_exp) > 4 else None)

explanation_lime_ranking = {
    'descriptor': list_desc_lime,
    'predicted_property': prop_lime,
    'top1': top1_lime,
    'top2': top2_lime,
    'top3': top3_lime,
    'top4': top4_lime,
    'top5': top5_lime
}

explanation_shap_ranking = {
    'descriptor': list_desc_shap,
    'predicted_property': prop_shap,
    'top1': top1_shap,
    'top2': top2_shap,
    'top3': top3_shap,
    'top4': top4_shap,
    'top5': top5_shap
}

df_top_exp_lime = pd.DataFrame(explanation_lime_ranking)
df_top_exp_shap = pd.DataFrame(explanation_shap_ranking)

In [69]:
df_top_exp_lime

,descriptor,predicted_property,top1,top2,top3,top4,top5
0,Physicochemical,Rotational constant A: GHz,MolWt,TPSA,NumHDonors,MolLogP,NumAromaticRings
1,3D,Internal energy at 0 K (U0): Hartree (Ha),RadiusOfGyration,Asphericity,NPR1,SpherocityIndex,NPR2
2,EState,Internal energy at 0 K (U0): Hartree (Ha),EState_34,EState_35,EState_33,EState_36,EState_23
3,Avalon,Rotational constant A: GHz,Avalon_Bit_328,Avalon_Bit_176,Avalon_Bit_42,Avalon_Bit_104,Avalon_Bit_131
4,CM,Internal energy at 0 K (U0): Hartree (Ha),CM_0_1,CM_0_3,CM_0_2,CM_0_5,CM_0_7
5,Pattern,Rotational constant A: GHz,Pattern_Bit_507,Pattern_Bit_181,Pattern_Bit_62,Pattern_Bit_497,Pattern_Bit_148
6,Topological,Internal energy at 0 K (U0): Hartree (Ha),Topo_Bit_371,Topo_Bit_50,Topo_Bit_51,Topo_Bit_315,Topo_Bit_94
7,Morgan,Internal energy at 0 K (U0): Hartree (Ha),Morgan2_Bit_295,Morgan2_Bit_314,Morgan2_Bit_144,Morgan2_Bit_183,Morgan2_Bit_138
8,Pattern,Internal energy at 0 K (U0): Hartree (Ha),Pattern_Bit_244,Pattern_Bit_213,Pattern_Bit_434,Pattern_Bit_369,Pattern_Bit_403
9,EState,Rotational constant A: GHz,EState_6,EState_25,EState_14,EState_33,EState_18
10,AtomPair,Rotational constant A: GHz,AtomPair_Bit_26,AtomPair_Bit_5,AtomPair_Bit_212,AtomPair_Bit_144,AtomPair_Bit_352
11,Avalon,Internal energy at 0 K (U0): Hartree (Ha),Avalon_Bit_340,Avalon_Bit_114,Avalon_Bit_441,Avalon_Bit_502,Avalon_Bit_391
12,Topological,Rotational constant A: GHz,Topo_Bit_321,Topo_Bit_208,Topo_Bit_510,Topo_Bit_55,Topo_Bit_168
13,MorganCount,Rotational constant A: GHz,Morgan2_Bit_33,Morgan2_Bit_138,Morgan2_Bit_295,Morgan2_Bit_356,Morgan2_Bit_279
14,AtomPair,Internal energy at 0 K (U0): Hartree (Ha),AtomPair_Bit_256,AtomPair_Bit_492,AtomPair_Bit_456,AtomPair_Bit_480,AtomPair_Bit_460
15,Physicochemical,Internal energy at 0 K (U0): Hartree (Ha),MolWt,TPSA,NumHAcceptors,NumRotatableBonds,QED
16,3D,Rotational constant A: GHz,Asphericity,RadiusOfGyration,NPR1,NPR2,SpherocityIndex
17,MorganCount,Internal energy at 0 K (U0): Hartree (Ha),Morgan2_Bit_295,Morgan2_Bit_144,Morgan2_Bit_239,Morgan2_Bit_348,Morgan2_Bit_337
18,Morgan,Rotational constant A: GHz,Morgan2_Bit_36,Morgan2_Bit_33,Morgan2_Bit_285,Morgan2_Bit_294,Morgan2_Bit_314
19,CM,Rotational constant A: GHz,CM_0_1,CM_0_5,CM_0_8,CM_0_2,CM_0_7

In [70]:
df_top_exp_shap

,descriptor,predicted_property,top1,top2,top3,top4,top5
0,Physicochemical,Rotational constant A: GHz,TPSA,MolWt,BalabanJ,NumHAcceptors,MolLogP
1,3D,Internal energy at 0 K (U0): Hartree (Ha),RadiusOfGyration,Asphericity,NPR1,SpherocityIndex,NPR2
2,EState,Internal energy at 0 K (U0): Hartree (Ha),EState_35,EState_34,EState_33,EState_25,EState_14
3,Avalon,Rotational constant A: GHz,Avalon_Bit_368,Avalon_Bit_124,Avalon_Bit_158,Avalon_Bit_246,Avalon_Bit_417
4,CM,Internal energy at 0 K (U0): Hartree (Ha),CM_0_2,CM_0_0,CM_0_1,CM_0_5,CM_0_3
5,Pattern,Rotational constant A: GHz,Pattern_Bit_497,Pattern_Bit_41,Pattern_Bit_452,Pattern_Bit_367,Pattern_Bit_163
6,Topological,Internal energy at 0 K (U0): Hartree (Ha),Topo_Bit_94,Topo_Bit_413,Topo_Bit_252,Topo_Bit_376,Topo_Bit_159
7,Morgan,Internal energy at 0 K (U0): Hartree (Ha),Morgan2_Bit_144,Morgan2_Bit_295,Morgan2_Bit_138,Morgan2_Bit_314,Morgan2_Bit_356
8,Pattern,Internal energy at 0 K (U0): Hartree (Ha),Pattern_Bit_41,Pattern_Bit_310,Pattern_Bit_257,Pattern_Bit_434,Pattern_Bit_367
9,EState,Rotational constant A: GHz,EState_0,EState_1,EState_2,EState_3,EState_4
10,AtomPair,Rotational constant A: GHz,AtomPair_Bit_232,AtomPair_Bit_484,AtomPair_Bit_288,AtomPair_Bit_492,AtomPair_Bit_52
11,Avalon,Internal energy at 0 K (U0): Hartree (Ha),Avalon_Bit_328,Avalon_Bit_340,Avalon_Bit_98,Avalon_Bit_143,Avalon_Bit_494
12,Topological,Rotational constant A: GHz,Topo_Bit_321,Topo_Bit_510,Topo_Bit_376,Topo_Bit_232,Topo_Bit_169
13,MorganCount,Rotational constant A: GHz,Morgan2_Bit_33,Morgan2_Bit_138,Morgan2_Bit_295,Morgan2_Bit_507,Morgan2_Bit_356
14,AtomPair,Internal energy at 0 K (U0): Hartree (Ha),AtomPair_Bit_424,AtomPair_Bit_224,AtomPair_Bit_57,AtomPair_Bit_56,AtomPair_Bit_492
15,Physicochemical,Internal energy at 0 K (U0): Hartree (Ha),MolWt,TPSA,NumRotatableBonds,MolLogP,NumHAcceptors
16,3D,Rotational constant A: GHz,RadiusOfGyration,Asphericity,NPR1,NPR2,SpherocityIndex
17,MorganCount,Internal energy at 0 K (U0): Hartree (Ha),Morgan2_Bit_144,Morgan2_Bit_295,Morgan2_Bit_33,Morgan2_Bit_414,Morgan2_Bit_507
18,Morgan,Rotational constant A: GHz,Morgan2_Bit_33,Morgan2_Bit_36,Morgan2_Bit_138,Morgan2_Bit_167,Morgan2_Bit_360
19,CM,Rotational constant A: GHz,CM_0_5,CM_0_1,CM_0_2,CM_0_8,CM_0_7